version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16


    working_directory: ~/client


    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
  deploy:
    machine:
      enabled: true
    working_directory: ~/client
  
  
    steps:
      - add_ssh_keys:
          fingerprints:
            - "48:e4:3e:c4:d3:c7:99:95:5b:64:86:a2:46:7f:98:8f"
      - checkout
      - run:
          name: Push Master to Production
          command: |
            git push https://github.com/Shaakirahkomolafe/scheduler.git master:production

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: production
      - deploy:
          filters:
            branches:
              ignore: production
          requires:
            - build
